name = "lectures"
defaultTargets = ["Lectures"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.32.0"

[[lean_lib]]
name = "Lectures"

[[lean_exe]]
name = "lectures-en"
root = "LecturesEnMain"

[[lean_exe]]
name = "lectures-pt"
root = "LecturesPtMain"
